sudo: required
language: php
php:
  - '7.0'
services:
  - docker
addons:
  code_climate:
    repo_token: 209d9fb51cdb22ee01f0937b3fb201a7e2de2d866a430113c3f5e76bd14632ed
install:
  - sudo service mysql stop
  - ./install.sh
before_script:
  - docker-compose up -d
script:
  - phpunit
after_script:
  - docker-compose down
  - CODECLIMATE_REPO_TOKEN=209d9fb51cdb22ee01f0937b3fb201a7e2de2d866a430113c3f5e76bd14632ed ./vendor/bin/test-reporter
after_success:
  - vendor/bin/test-reporter