sudo: required
language: php
php:
  - '5.6'
services:
  - docker
install:
  - sudo service mysql stop
  - ./install.sh
before_script:
  - docker-compose up -d
script:
  - docker-compose run -u laradock workspace php -dzend_extension=xdebug.so vendor/bin/phpunit
after_success:
  - docker-compose run -u laradock -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_TOKEN workspace vendor/bin/test-reporter
after_script:
  - docker-compose down